version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANJSON1Project
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.mjanjson1.integrations:doct
  packages:
  - name: MJANJSON1Project
    version: "1.0"
